Core/Core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mangement/',include('LMS.urls')),
    path("",include('home.urls')),
    path("accounts/",include('accounts.urls'))
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

Core/LMS/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.Index,name='mangment'),
    path('books/',views.Books,name='mang_books'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('profiles/',views.profiles,name='profiles'),
    path('delete_user/<int:id>',views.delete_user,name='delete_user'),
    path('upgrade_user/<int:id>',views.givePermission,name='givePermission'),
    path('downgrade_user/<int:id>',views.takePermission,name='takePermission')

]

Core/accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    path("SignUp/",views.signup_view,name='signup'),
    path("login/",views.login_view,name="login"),
    path("logout/",views.logOut,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit/',views.profile_edit,name='profile_edit'),
]

Core/accounts/models.py
from django.db import models

from django.contrib.auth.models import User 

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

def upload_pics(inctence,pic):
    return f"Profiles/{inctence.id}.{pic.split('.')[1]}"


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    address= models.CharField(max_length=50, blank=True, null=True)
    phone_number=models.CharField(max_length=15,null=True,blank=True)
    user_photo=models.ImageField(upload_to=upload_pics,null=True,blank=True)
    borrowedBooks=models.IntegerField(default=0)
    boughtBooks=models.IntegerField(default=0)
    def __str__(self) :
        if self.user.first_name =='' or self.user.first_name == None:
            return self.user.username
        return self.user.first_name + " "+ self.user.last_name
    
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

Core/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from .form import SignUpForm,EditProfileForm,EditUserForm
from django.contrib.auth import authenticate, login,logout
from .models import Profile
# Create your views here.



def login_view(request):
    context={}
    if request.method == "POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is None:
            context={"error":"اسم المستخدم او كلمة المرور غير صحيحة"}
            return render(request,"accounts/login.html",context)
        login(request,user)
        return redirect('/')
    return render(request,"accounts/login.html",context)



def signup_view(request):
    if request.method == "POST":
        form=SignUpForm(request.POST)
        if form.is_valid : 
            form.save()
            user=authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password1'])
            login(request,user)
            return redirect('accounts:profile')
        else:
            form=SignUpForm()
            return render(request,'accounts/signup.html',{'form':form,'error':form.errors})

    form=SignUpForm()
    return render(request,'accounts/signup.html',{'form':form})
    




@login_required
def logOut(request):
    logout(request)
    return redirect('/')


@login_required
def profile(request):
    profile=get_object_or_404(Profile,user=request.user)
    return render(request,'accounts/profile.html',{"profile":profile})

@login_required
def profile_edit(request):
    profile = get_object_or_404(Profile,user=request.user)
    if request.method == 'POST':
        formProfile = EditProfileForm(request.POST,request.FILES ,instance=profile)
        formUser=EditUserForm(request.POST,instance=profile.user)
        if formUser.is_valid() and formProfile.is_valid():
            formUser.save()
            myprofile = formProfile.save(commit=False)
            myprofile.user=request.user
            myprofile.save()
            return redirect('accounts:profile')
    return render(request,"accounts/profile_edit.html",{"profile":profile})


    
    

Core/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  	<meta charset="UTF-8">
  	<title>{% block Title %}{% endblock Title %}</title>
	<link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/2232/2232688.png" type="image/x-icon">
  	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/login_style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
{% block content %}
{% endblock content %}

<!-- partial -->
  
</body>
</html>

Core/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block Title %}تسجيل الدخول {% endblock Title %}

{% block content %}



{% if next %}
{% if user.is_authenticated %}
<p>هذا الحساب ليس لديه حق الوصول لهذه الصفحة ارجاء ادخال الحساب ذو صلاحيات لدخول الى هذه الصفحة</p>
{% else %}
<p>ارجو تسجيل الدخول لدخول إلى هذه الصفحة</p>
{% endif %}
{% endif %}
<style>
  .box-form .left {
    background-image: url("/static/imeges/lib1.jpg");
  }
</style>
<form method="post" action="{% url 'accounts:login' %}">
  {% csrf_token %}
  <div class="box-form">
    <div class="left">
      <div class="overlay">
        <h1>أهلا بعودتك </h1>
        <p>اهلا بكم في مكتبتكم المكتبة العالمية</p>
      </div>
    </div>


    <div class="right">
      <h5>تسجيل الدخول</h5>
      <p>ليس لديك حساب ؟ <a href="{% url 'accounts:signup' %}">التسجيل</a> لن يستغرق الامر اكثر من دقيقة</p>
      <div class="inputs">
        <p style="color:red;">{{error}}</p>
        {% if next %}
        {% if user.is_authenticated %}
        <p>هذا الحساب ليس لديه حق الوصول لهذه الصفحة ارجاء ادخال الحساب ذو صلاحيات لدخول الى هذه الصفحة</p>
        {% else %}
        <p>ارجو تسجيل الدخول لدخول إلى هذه الصفحة</p>
        {% endif %}
        {% endif %}
        <input type="text" name="username" placeholder="أسم المستخدم">
        <br>
        <input type="password" name="password" placeholder="كلمة المرور">
      </div>

      <br><br>

      <div class="remember-me--forget-password">
        <!-- Angular -->
        <label>
          <input type="checkbox" name="item" checked />
          <span class="text-checkbox">تذكرني</span>
        </label>
        <p>نسيت كلمة المرور</p>
      </div>

      <br>
      <button type="submit">ادخل</button>
    </div>

  </div>


  <input type="hidden" name="next" value="{{ next }}">
</form>


{% endblock %}

Core/templates/accounts/profile.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="p-16">
    <div class="p-8 bg-white shadow mt-24">
      <div class="grid grid-cols-1 md:grid-cols-3">
        <div class="grid grid-cols-3 text-center order-last md:order-first mt-20 md:mt-0">
          <div>
            <p class="font-bold text-gray-700 text-xl">{{profile.borrowedBooks}}</p>
            <p class="text-gray-400">الكتب المشترى</p>
          </div>
          <div>
            <p class="font-bold text-gray-700 text-xl">{{profile.boughtBooks}}</p>
            <p class="text-gray-400">الكتب المستأجرة</p>
          </div>
        </div>
        <div class="relative">
          {% if profile.user_photo %}     
          <div>
            <img src="{{profile.user_photo.url}}" 
            class="w-48 h-48 bg-indigo-100 mx-auto rounded-full shadow-2xl absolute inset-x-0 top-0 -mt-24 flex items-center justify-center text-indigo-500" alt="">
          </div>
          {% else %}
          <div
            class="w-48 h-48 bg-indigo-100 mx-auto rounded-full shadow-2xl absolute inset-x-0 top-0 -mt-24 flex items-center justify-center text-indigo-500">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-24 w-24" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
            </svg>
          </div>
          {% endif %}
        </div>

       {% if user.is_superuser and not profile.user.is_staff %}
        <div class="space-x-8 flex justify-between mt-32 md:mt-0 md:justify-center">
          <button
            class="text-white py-2 px-4 uppercase rounded bg-blue-400 hover:bg-blue-500 shadow hover:shadow-lg font-medium transition transform hover:-translate-y-0.5">
            ترقية الى مسوؤل
          </button>
        </div>
      </div>
      {% endif %}
      {% if request.user == profile.user %}
      <div class="space-x-8 flex justify-between mt-32 md:mt-0 md:justify-center">
        <a href="{% url 'accounts:profile_edit' %}"
          class="text-white py-2 px-4 uppercase rounded bg-sky-400 hover:bg-sky-500 shadow hover:shadow-lg font-medium transition transform hover:-translate-y-0.5">
          تعديل بيانات الحساب
      </a>
      </div>
      {% endif %}
      </div>
      <div class="mt-20 text-center border-b pb-12">
        <h1 class="text-4xl font-medium text-gray-700">@{{profile.user.username}}</h1>
        <p class="font-light text-gray-600 mt-3">{{profile}}</p>
      </div>
  
  <div class="mt-12 flex flex-col justify-center">
    <div class="mb-4">
      <label class="text-gray-600">الاسم بالكامل</label>
      <p id="name" class="form-control-static">{{profile}}</p>
    </div>
    <div class="mb-4">
      <label class="text-gray-600">اسم المستخدم</label>
      <p id="name" class="form-control-static">{{profile.user.username}}</p>
    </div>
    <div class="mb-4">
      <label class="text-gray-600">البريد الالكتروني</label>
      <p id="email" class="form-control-static">{{profile.user.email}}</p>
    </div>
    <div class="mb-4">
      <label class="text-gray-600">رقم الهاتف</label>
      <p id="phone_number" class="form-control-static">{{profile.phone_number}}</p>
    </div>
    <div class="mb-4">
      <label class="text-gray-600">العنوان</label>
      <p id="address" class="form-control-static">{{profile.address}}</p>
    </div>
    <div class="mb-4">
      <label class="text-gray-600">الحالة</label>
      {% if user.is_superuser %}
      <p id="staff" class="form-control-static">صاحب المكتبة</p>
      {% elif user.is_staff %}
        <p id="staff" class="form-control-static">عسوؤل في المكتبة</p>
      {% else %}
        <p id="staff" class="form-control-static">عضو في المكتبة</p>
      {% endif %}
      
      
    </div>
  </div>
  
    </div>
  </div>
{% endblock content %}

Core/templates/accounts/profile_edit.html
{% extends 'home/base.html' %}

{% block content %}
<div class="p-16">
    <div class="p-8 bg-white shadow mt-24">
        <div class="grid grid-cols-1 md:grid-cols-3">
            <div class="grid grid-cols-3 text-center order-last md:order-first mt-20 md:mt-0">
                <div>
                    <p class="font-bold text-gray-700 text-xl">{{profile.borrowedBooks}}</p>
                    <p class="text-gray-400">الكتب المشترى</p>
                </div>
                <div>
                    <p class="font-bold text-gray-700 text-xl">{{profile.boughtBooks}}</p>
                    <p class="text-gray-400">الكتب المستأجرة</p>
                </div>
            </div>
            <div class="relative">
                {% if profile.user_photo %}
                <div>
                    <img src="{{profile.user_photo.url}}"
                        class="w-48 h-48 bg-indigo-100 mx-auto rounded-full shadow-2xl absolute inset-x-0 top-0 -mt-24 flex items-center justify-center text-indigo-500"
                        alt="">
                </div>
                {% else %}
                <form method="POST" enctype="multipart/form-data">
                    <input type="file" name="user_photo" class="hidden" id="upload-photo">
                    <label for="upload-photo"
                        class="w-48 h-48 bg-indigo-100 mx-auto rounded-full shadow-2xl absolute inset-x-0 top-0 -mt-24 flex items-center justify-center text-indigo-500 cursor-pointer">رفع
                        الصورة</label>
                    <button type="submit" class="hidden">رفع صورة</button>

            </div>
            {% endif %}
        </div>

        {% if user.is_superuser and not profile.user.is_staff %}
        <div class="space-x-8 flex justify-between mt-32 md:mt-0 md:justify-center">
            <button
                class="text-white py-2 px-4 uppercase rounded bg-blue-400 hover:bg-blue-500 shadow hover:shadow-lg font-medium transition transform hover:-translate-y-0.5">
                ترقية الى مسوؤل
            </button>
        </div>
        {% endif %}
        <div class="space-x-8 flex justify-between mt-32 md:mt-0 md:justify-center">
            {% if profile.user_photo %}
            <form method="POST" enctype="multipart/form-data">
                <input type="file" name="user_photo" class="hidden" id="upload-photo">
                <label for="upload-photo"
                    class="text-white py-2 px-4 uppercase rounded bg-indigo-500 shadow hover:shadow-lg font-medium transition transform hover:-translate-y-0.5">تغيرالصورة</label>
                {% endif %}
        </div>
    </div>
    <div class="mt-20 text-center border-b pb-12">
        <h1 class="text-4xl font-medium text-gray-700">{{profile}}</h1>
        <p class="font-light text-gray-600 mt-3">{{profile.address}}</p>
    </div>

    <div class="mt-12 flex flex-col justify-center">
        <form method="POST" enctype="multipart/form-data" class="w-full">
            {% csrf_token %}
            <div class="mb-4">
                <label class="text-gray-600 block">الإسم الاول</label>
                <input type="text" name="first_name" value="{{profile.user.first_name}}"
                    class="w-full px-4 py-2 border border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 rounded-md shadow-sm">
            </div>
            <div class="mb-4">
                <label class="text-gray-600 block">الاسم الاخير</label>
                <input type="text" name="last_name"
                    class="w-full px-4 py-2 border border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 rounded-md shadow-sm"
                    value="{{profile.user.last_name}}">
            </div>
            <div class="mb-4">
                <label class="text-gray-600 block">البريد الالكتروني</label>
                <input type="email" name="email" value="{{profile.user.email}}"
                    class="w-full px-4 py-2 border border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 rounded-md shadow-sm">
            </div>
            <div class="mb-4">
                <label class="text-gray-600 block">العنوان</label>
                <input type="address" name="address" value="{{profile.address}}"
                    class="w-full px-4 py-2 border border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 rounded-md shadow-sm">
            </div>
            <div class="mb-4">
                <label class="text-gray-600 block">اسم المستخدم</label>
                <input type="text" name="username" value="{{profile.user.username}}"
                    class="w-full px-4 py-2 border border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 rounded-md shadow-sm">
            </div>
            <div class="mb-4">
                <label class="text-gray-600 block">رقم الهاتف</label>
                <input type="text" name="phone_number" value="{{profile.phone_number}}"
                    class="w-full px-4 py-2 border border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 rounded-md shadow-sm">
            </div>
            <div class="flex justify-center">
                <button type="submit"
                    class="text-white py-2 px-4 uppercase rounded bg-indigo-500 shadow hover:shadow-lg font-medium transition transform hover:-translate-y-0.5">
                    حفظ التغييرات
                </button>
        </form>
        </form>
    </div>

</div>
</div>
{% endblock content %}

Core/templates/accounts/profile_page.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="container mx-auto">
    <div class="flex flex-col items-center">
      <img src="{{ profile.user_photot.url }}" alt="User Photo" class="rounded-full w-32 h-32" />
      <h4 class="mt-4">{{ profile.user.first_name }} {{ profile.user.last_name }}</h4>
      <p class="text-gray-500">{{ profile.user.username }}</p>
      <p class="text-gray-500">{{ profile.address }}</p>
      <p class="text-gray-500">{{ profile.phone_number }}</p>
      <p class="text-gray-500">Borrowed Books: {{ profile.borrowedBooks }}</p>
    </div>
  </div>
{% endblock %}

Core/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block Title %} إنشاء حساب {% endblock Title %} 
{% block content %}
<style>
    .box-form .left {
      background-image: url("/static/imeges/lib2.jpg");
    }
    
   </style>
<form method="post" >
       {% csrf_token %}
    <div class="box-form">
	<div class="left">
		<div class="overlay">
		<h1>إنشاء حساب جديد</h1>
		<p>اهلا بكم في مكتبتكم المكتبة العالمية</p>
		</div>
	</div>
	
	
		<div class="right">
		<h5>
             إنشاء حساب 

        </h5>
		<p>هل لديك حساب بالفعل ؟ <a href="{% url 'accounts:login' %}">تسجيل الدخول</a> </p>
		<div class="inputs">
			{% for i in error  %}
			<p style="color:red;">{{i.message}}</p>
			{% endfor %}
            <input type="text" name="first_name" placeholder="ألإسم الاول ">
			<input type="text" name="last_name" placeholder="الإسم الاخير">
			<input type="text" name="username" placeholder="أسم المستخدم">
			<input type="email" name="email" placeholder="البريد الإلكتروني">
            <br>
			<input type="password" name="password1" placeholder="كلمة المرور">
			<input type="password" name="password2" placeholder="تأكيد كلمة المرور">
		</div>
			
			<br><br>
			
		<div class="remember-me--forget-password">
	<label>
		<input type="checkbox" name="item" checked/>
		<span class="text-checkbox">تذكرني</span>
	</label>
		</div>
			
			<br>
            <button type="submit" >إنشاء</button>	</div>
	
</div>
</form>

{% endblock  %}