Core/Core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mangement/',include('LMS.urls')),
    path("",include('home.urls')),
    path("accounts/",include('accounts.urls'))
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

Core/LMS/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.Index,name='mangment'),
    path('books/',views.Books,name='mang_books'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('profiles/',views.profiles,name='profiles'),
    path('delete_user/<int:id>',views.delete_user,name='delete_user'),
    path('upgrade_user/<int:id>',views.givePermission,name='givePermission'),
    path('downgrade_user/<int:id>',views.takePermission,name='takePermission')

]

Core/accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    path("SignUp/",views.signup_view,name='signup'),
    path("login/",views.login_view,name="login"),
    path("logout/",views.logOut,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit/',views.profile_edit,name='profile_edit'),
]

Core/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("",views.index,name='index'),
    path('book/<int:id>',views.bookDetails,name='bookDetails'),
    path("books/",views.books,name="books")
]

Core/home/models.py
from django.db import models

# Create your models here.

Core/home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator
from LMS.models import Book
from accounts.models import Profile
# Create your views here.


def index(request):
    newBooks=Book.objects.all()[:4]
    return render(request,'home/index.html',{"newBooks":newBooks})

def bookDetails(request ,id ):
    book=get_object_or_404(Book,id=id)
    return render(request,"home/bookDetail.html",{"book":book})




def books(request):
    books=Book.objects.all()
    paginator = Paginator(books, 10)
    page_number=request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,"home/books.html",{"books":page_obj})



    

Core/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html  lang="ar">
  
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/2232/2232688.png" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
        <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'js/tailwind.js' %}"></script>

      
        
        <title>المكتبة العالمية</title>
      </head>
  
<body dir="rtl" class="hold-transition sidebar-mini">
<!-- Navigation Bar -->
<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 left-0 border-b border-gray-200 dark:border-gray-600">
  <!-- Navbar content -->
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="{% url 'index' %}" class="flex items-center">
      <img src="{% static 'imeges/logo.png' %}" class="h-8 ml-3" alt="">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">المكتبة العالمية</span>
    </a>
    <div class="flex md:order-1">
      <form class="hidden lg:mr-4" method="get">
        <div class="relative">
          <input
            class="border-2 border-transparent bg-gray-800 text-gray-100 rounded-full focus:outline-none focus:border-teal-500 pl-10 pr-4 py-2  "
            type="search" name="search" placeholder="بحث" action="">
          <div class="absolute top-0 left-0 mt-2 ml-3">
            <i class="fas fa-search text-gray-500"></i>
          </div>
        </div>
      </form>
      <input type="checkbox" id="menu-toggle-mobile" class="hidden">
      <label for="menu-toggle-mobile"
        class="fixed top-0 right-0 mt-5 mr-48 text-white absolute cursor-pointer sm:hidden">
        <i class="fas fa-bars text-2xl"></i>
      </label>
      <div class="hidden sm:hidden" id="mobile-menu">
        <a href="{% url 'index' %}"
          class="block py-2 px-4 text-lg font-semibold text-slate-50 hover:text-slate-500">الصفحة الرئيسية</a>
        <a href="{% url 'books' %}"
          class="block py-2 px-4 text-lg font-semibold text-slate-50 hover:text-slate-500">الكتب</a>
        <a href="#" class="block py-2 px-4 text-lg font-semibold text-slate-50 hover:text-slate-500">إتصل بنا</a>
        {% if user.is_superuser or user.is_staff %}
        <a href="{% url 'accounts:profile' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-amber-700 text-white rounded-xl hover:bg-amber-900">حساب
          الشخصي</a>
        <a href="{% url 'mangment' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-blue-700 text-white rounded-xl hover:bg-blue-900">صفحة
          الادارة</a>
        <a href="{% url 'accounts:logout' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-rose-700 text-white rounded-xl hover:bg-rose-900">تسجيل
          الخروج</a>
        {% elif user.is_authenticated %}
        <a href="{% url 'accounts:profile' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-amber-700 text-white rounded-xl hover:bg-amber-900">حساب
          الشخصي</a>
        <a href="{% url 'accounts:logout' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-rose-700 text-white rounded-xl hover:bg-rose-900">تسجيل
          الخروج</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-amber-700 text-white rounded-xl hover:bg-amber-900">تسجيل</a>
        <a href="{% url 'accounts:login' %}"
          class="block py-2 px-4 text-lg mt-3 font-semibold bg-teal-700 text-white rounded-xl hover:bg-teal-900">تسجيل
          الدخول</a>
        {% endif %}
      </div>
    </div>
   <div class="items-center justify-between hidden w-full md:flex md:w-auto " ">
    <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="{% url 'index' %}" class="block py-2 pl-3 mr-5 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" >الصفحة الرئيسية</a>
      </li>
      <li>
        <a href="{% url 'books' %}" class="block py-2 pl-3 mr-5 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">الكتب</a>
      </li>
      <li>
        <a href="#" class="block py-2 pl-3 mr-2 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">إتصل بنا</a>
      </li>
    </ul>
    
  </div>
      {% if user.is_superuser or user.is_staff  %}
        <a class="px-6 py-2 mr-1 text-lg font-semibold bg-amber-700 text-white rounded-xl hover:bg-amber-900 hidden md:inline-block  lg:inline-block" href="{% url 'accounts:profile' %}">الحساب الشخصي</a> 
        <a class=" px-6 py-2 mr-1 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700 hidden md:inline-block lg:inline-block" href="{% url "mangment" %}">صفحة الادارة</a>
        <a class="px-6 py-2 mr-1 text-lg font-semibold bg-rose-700 text-white rounded-xl hover:bg-rose-900 hidden md:inline-block  lg:inline-block" href="{% url 'accounts:logout' %}">تسجيل الخروج </a>
      {% elif user.is_authenticated  %}
        <a class="px-6 py-2 mr-1 text-lg font-semibold bg-amber-700 text-white rounded-xl hover:bg-amber-900 hidden md:inline-block lg:inline-block" href="{% url 'accounts:profile' %}">الحساب الشخصي</a>
        <a class="px-6 py-2 mr-1 text-lg font-semibold bg-rose-700 text-white rounded-xl hover:bg-rose-900 hidden  md:inline-block lg:inline-block" href="{% url 'accounts:logout' %}">تسجيل الخروج </a>
      {% else %}
        <a class=" px-6 py-2  text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 hidden md:inline-block   lg:inline-block" href="{% url "accounts:login" %}">تسجيل الدخول</a>
        <a class="px-6 py-2  text-lg font-semibold bg-amber-700 text-white rounded-xl hover:bg-amber-900 hidden  md:inline-block  lg:inline-block" href="{% url 'accounts:signup' %}">التسجيل</a>     
      {% endif %}
 
  </div>
</nav>  

{% block content %}
{% endblock %}
 <!-- Footer -->
 <footer id='footer' class="fixed bottom-0 left-0 z-20 w-full p-4 bg-white border-t border-gray-200 shadow hidden md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">كل الحقوق محفوظة © 2023 
    </span>
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400"> تم التطوير بواسطة <a href="https://www.facebook.com/badr.alden.374/" class="hover:underline">بدر الدين</a> & <a href="https://www.facebook.com/profile.php?id=100004292080672" class="hover:underline">تاج الدين</a></span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 ">
        <li>
            <a href="#" class="mr-4 hover:underline md:mr-6">حول </a>
        </li>
        <li>
            <a href="#" class="mr-4  hover:underline md:mr-6 ">الضوابط القوانين</a>
        </li>
        <li>
            <a href="#" class="mr-4  hover:underline md:mr-6">الترخيص </a>
        </li>
        <li>
            <a href="#" class="mr-4  hover:underline sm:hidden">تواصل معنا </a>
        </li>
    </ul>
</footer>
<!-- Scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    // Toggle mobile menu
    $('#menu-toggle-mobile').change(function () {
      var mobileMenu = $('#mobile-menu');
      if ($(this).is(':checked')) {
        mobileMenu.removeClass('hidden');
      } else {
        mobileMenu.addClass('hidden');
      }
    });

    // Close mobile menu on outside click
    $(document).click(function (e) {
      var target = $(e.target);
      var mobileMenu = $('#mobile-menu');
      var menuToggle = $('#menu-toggle-mobile');
      if (!target.is(mobileMenu) && !target.is(menuToggle) && mobileMenu.has(e.target).length === 0) {
        mobileMenu.addClass('hidden');
        menuToggle.prop('checked', false);
      }
    });
  });
</script>

</body>
</html>

Core/templates/home/bookDetail.html
{% extends 'home/base.html' %}

{% block content %} 
  <!-- Page Content -->
  <div class="container mx-auto px-4 mt-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div>
        <img class="book-img" src="{{book.photo_book.url}}" alt="Book Image">
      </div>
      <div>
        <h1 class="book-title">تفاصيل الكتاب</h1>
        <p class="book-description">كتاب يتحدث عن بعض أسماء الله الحسنى وكيف نعيشها في حياتنا حرص المؤلف أن يكون الكتاب مناسباً لمن هم متوسطي الثقافة، ويكون ناسباً للمحتاج و المريض و السليم

            هذا الكتاب من تأليف علي جابر الفيفي و حقوق الكتاب محفوظة لصاحبها</p>
        <p class="book-price">السعر:  ${{book.price}}</p>
        <button class="px-6 py-2 mt-4 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">إضافة إلى السلة</button>
      </div>
    </div>
  </div>
{% endblock content %}

Core/templates/home/books.html
{% extends 'home/base.html' %}

{% block content %}
<section class="bg-gray-100 py-8">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold mb-4">الكتب</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <!-- Book 1 -->
        {% for book  in books  %}
        <a href="{% url 'bookDetails' book.id %}"> 
          <div class="col-lg-4 col-md-6 mb-4">
           <div class="card h-100">
             <img class="card-img-top" src="{{book.photo_book.url}}" alt="Book 1">
              <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
               <p class="card-text">{{book.author}} </p>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
        
      </div>
    </div>
  </section>
{% endblock %}

Core/templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container mx-auto px-4">
  <div class="mt-8">
    <h1 class="text-3xl font-semibold">مرحبًا بكم في مكتبتنا!</h1>
    <p class="mt-2">استكشف مجموعتنا الواسعة من الكتب.</p>
  </div>

  <!-- Book Section -->

  <div class="mt-8">
  <h2 class="text-2xl font-semibold">الكتب الجديدة</h2>
  </div>
  
    
    <div class="mt-6">
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {% for book  in newBooks  %}
      <a href="{% url 'bookDetails' book.id %}"> 
        <div class="col-lg-4 col-md-6 mb-4">
         <div class="card h-100">
           <img class="card-img-top" src="{{book.photo_book.url}}" alt="Book 1">
            <div class="card-body">
              <h5 class="card-title">{{book.title}}</h5>
             <p class="card-text">{{book.author}} </p>
            </div>
          </div>
        </div>
      </a>
        {% endfor %}
      </div>
    </div>
   
</div>
 
  {% endblock  %}

Core/templates/home/profiles.html
<head>
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:300,400,600i&display=swap" rel="stylesheet">
</head>
<header> <a href="https://codepen.io/LIMESTA/pen/VwZNmJE"> Click here to check out V2 utilizing SCSS </a> </header>
<div class="infocardContainer">
  <div id="main">
    <img src="https://upload.wikimedia.org/wikipedia/commons/e/ea/Dog_coat_variation.png"></img>
  </div>
  <div id="textbois">
    <h2>Emil Alicic</h2>
    <h4>Professional Memeologist</h4>
    <a href="mailto:limecicila@gmail.com">limecicila@gmail.com</a>
    <div id="hotlinks">
      <a href="https://codepen.io/LIMESTA"><img id="codepenio" src="https://blog.codepen.io/wp-content/uploads/2012/06/Button-Fill-Black-Small.png" target="_blank"></img>
      </a>
      <a href="https://codepen.io/LIMESTA">
        <img id="codepenio" src="https://blog.codepen.io/wp-content/uploads/2012/06/Button-Fill-Black-Small.png" target="_blank"></img>
      </a>
      <a href="https://codepen.io/LIMESTA">
        <img id="codepenio" src="https://blog.codepen.io/wp-content/uploads/2012/06/Button-Fill-Black-Small.png" target="_blank"></img>
      </a>
    </div>
  </div>
</div>


<style>
    /*TODO: clean it all up, finish flex, add aesthetics, icons, redefine to be relative to vh-vw, maybe rework v2 variant using scss and frames and real transitions? */
    html body {
    background-color: black;
    margin: 0 0 0 0;
    }
    .infocardContainer * {
    font-family: 'Fira Sans Condensed', sans-serif;
    font-weight: 300;
    }
    h2 {
    font-weight: 600; font-style: italic; font-family: "Fira Sans Condensed", sans-serif;
    }
    header {
    height: 2em;
    background-color: #111122;
    margin: 0 0 0 0;
    padding: auto;
    font-size: 2em;
    text-align: center;
    line-height: 2em;
    color: white;
    }
    a {
    text-decoration: none;
    }
    a:visited {
    color: #555566;
    }
    a:hover {
    text-decoration: underline;
    }
    .infocardContainer {
    display: flex;
    height: 200px;
    width: 200px;
    border-radius: 100px;
    background: rgb(0,159,255);
    background: linear-gradient(121deg, rgba(255,255,255,0) 13%, rgba(0,159,255,1) 100%);
    transition: all 500ms ease-in;
    transition-delay: 1s;
    margin: auto;
    margin-top: 100px;
    --margin-top: 100px;
    }
    .infocardContainer:hover {
    width: 500px;
    border-radius: 100px 10px 100px 100px;
    transition: all 1s ease-out;
    }

    .infocardContainer div {
    text-color: white;
    flex-shrink: 1;
    width: 100%;
    --background-color: green;
    }
    .infocardContainer div * {
    display: flex;
    --flex: inherit;
    overflow: hidden;
    text-overflow: hidden;
    --background-color: yellow;
    color: white;
    white-space: nowrap;
    width: 0;
    height: auto;
    transition: all 450ms ease-in;
    transition-delay: 1s;
    }
    .infocardContainer:hover div *{
    --background-color: purple;
    display: flex;
    visibility: visible;
    transition: all 1s ease-out;
    transition-delay: 500ms;
    width: 100%;
    height: auto;
    }

    .infocardContainer #main, .infocardContainer #main img{
    --background-color: red;
    height: 200px;
    width: 200px;
    padding-right: 10px;
    border-radius: 100%;
    flex-shrink: 0;
    object-fit: cover;
    }
    .infocardContainer #main img{
    height: 180px;
    width: 180px;
    transition: none;
    display: float;
    position: relative;
    border: 10px solid white;
    margin: 0 0 0 0; padding: 0 0 0 0;
    }
    .infocardContainer #textbois {
    position: relative;
    }
    .infocardContainer #textbois #hotlinks {
    max-width: 60%;
    max-height: 30px;
    
    --background-color: white;
    position:absolute;
    bottom: 5px;
    display: flex;
    justify-content: space-between;
    border-radius: 13px;
    }
    .infocardContainer #textbois #hotlinks * {
    background-color: white;
    max-width: 30px;
    --margin: 0 1px 0 1px;
    border-radius: 25px;
    }
    /*TODO: animate copy main transition style for info*/
    .infocardContainer #textbois #hotlinks *:hover {
    
    
    }
</style>